fail build job, test job passes

diff --git a/.github/workflows/dev_workflow.yml b/.github/workflows/dev_workflow.yml
--- a/.github/workflows/dev_workflow.yml
+++ b/.github/workflows/dev_workflow.yml
@@ -15,8 +15,8 @@ jobs:
       - name: Test
         run: |
           echo "Current SHA: ${{ github.sha }}"
-          echo "Fail!"
-          exit 1
+          echo "Success!"
+          exit 0
   build:
     runs-on: ubuntu-latest
     steps:
@@ -24,5 +24,5 @@ jobs:
         run: |
           echo "Current SHA: ${{ github.sha }}"
           echo "Build Job"
-          echo "Success!"
-          exit 0
+          echo "Fail!"
+          exit 1
