fail dev job

diff --git a/.github/workflows/dev_workflow.yml b/.github/workflows/dev_workflow.yml
--- a/.github/workflows/dev_workflow.yml
+++ b/.github/workflows/dev_workflow.yml
@@ -15,8 +15,8 @@ jobs:
       - name: Test
         run: |
           echo "Current SHA: ${{ github.sha }}"
-          echo "Success!"
-          exit 0
+          echo "Fail!"
+          exit 1
   build:
     runs-on: ubuntu-latest
     steps:
