Fali dev workflow

diff --git a/.github/workflows/dev_workflow.yml b/.github/workflows/dev_workflow.yml
--- a/.github/workflows/dev_workflow.yml
+++ b/.github/workflows/dev_workflow.yml
@@ -15,5 +15,5 @@ jobs:
       - name: Test
         run: |
           echo "Current SHA: ${{ github.sha }}"
-          echo "Success!"
-          exit 0
+          echo "Failure!"
+          exit 1
