fail build job again

diff --git a/.github/workflows/dev_workflow.yml b/.github/workflows/dev_workflow.yml
--- a/.github/workflows/dev_workflow.yml
+++ b/.github/workflows/dev_workflow.yml
@@ -24,5 +24,5 @@ jobs:
         run: |
           echo "Current SHA: ${{ github.sha }}"
           echo "Build Job"
-          echo "Success!"
-          exit 0
+          echo "Fail!"
+          exit 1
