add new job to python tests head

diff --git a/.github/workflows/python_tests_head.yml b/.github/workflows/python_tests_head.yml
--- a/.github/workflows/python_tests_head.yml
+++ b/.github/workflows/python_tests_head.yml
@@ -50,3 +50,14 @@ jobs:
           pip install "git+https://github.com/danielibarrola/python-hello-world.git@$TARGET_SHA"
       - name: Test
         run: python tests/test_hello_world.py
+
+  build:
+    runs-on: ubuntu-latest
+    name: Test Build
+    steps:
+      - name: Build
+        run: |
+          echo "Current SHA: ${{ github.sha }}"
+          echo "Build Job"
+          echo "Fail!"
+          exit 1
